---
abstract: 'AnyEvent based Perl extension for validating YubiKey OTPs.'
author:
  - 'Dain Nilsson <dain@yubico.com>'
build_requires:
  ExtUtils::MakeMaker: 0
  Test::More: 0
  Test::Exception: 0
configure_requires:
  ExtUtils::MakeMaker: 0
distribution_type: module
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.57_05'
license: freebsd
resources:
  license: http://opensource.org/licenses/BSD-2-Clause
  homepage: https://github.com/Yubico/yubico-perl-client
  repository: https://github.com/Yubico/yubico-perl-client
  bugtracker: https://github.com/Yubico/yubico-perl-client/issues
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Yubico
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent::HTTP: 0
  UUID::Tiny: 0
  MIME::Base64: 0
  Digest::HMAC_SHA1: 0
  URI::Escape: 0
version: v0.9.0
